# Generated by Django 4.1.2 on 2023-10-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=1000)),
                ('sku', models.CharField(max_length=1000, unique=True)),
                ('unit', models.CharField(max_length=1000)),
                ('brand', models.CharField(max_length=1000)),
                ('category', models.CharField(choices=[(0, 'Boyes'), (1, 'Dry Cleaning'), (3, 'Grirls'), (4, 'IRONING'), (5, 'Laundry')], max_length=1000)),
                ('business_locations', models.CharField(max_length=1000)),
                ('alert_quantity', models.CharField(max_length=1000)),
                ('warranty', models.CharField(max_length=1000)),
            ],
        ),
    ]
