# Generated by Django 4.1.2 on 2023-10-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='category',
            field=models.CharField(choices=[(0, 'Boyes'), (1, 'Dry Cleaning'), (2, 'Grirls'), (3, 'IRONING'), (4, 'Laundry')], default='Boyes', max_length=1000),
        ),
    ]
