# Generated by Django 4.1.2 on 2023-10-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_addproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='category',
            field=models.CharField(choices=[(0, 'Boyes'), (1, 'Dry Cleaning'), (2, 'Grirls'), (3, 'IRONING'), (4, 'Laundry')], max_length=1000),
        ),
    ]
