# Generated by Django 4.1.2 on 2023-10-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_addproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='alert_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='category',
            field=models.IntegerField(choices=[(0, 'Boys'), (1, 'Dry Cleaning'), (2, 'Girls'), (3, 'Ironing'), (4, 'Laundry')]),
        ),
    ]
