# Generated by Django 4.1.2 on 2023-10-28 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_addproduct_brand_alter_addproduct_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warranty_name', models.CharField(max_length=100)),
                ('warranty_description', models.TextField()),
                ('warranty_duration', models.PositiveIntegerField(default=1)),
                ('warranty_duration_type', models.CharField(choices=[(0, 'Days'), (1, 'Months'), (2, 'Years')], default=0, max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='warranty',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.warranty'),
        ),
    ]
