# Generated by Django 4.1.2 on 2023-10-28 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_addproduct_brand_alter_addproduct_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='warranty',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.warranty'),
        ),
    ]
