# Generated by Django 4.1.2 on 2023-10-28 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_addproduct_warranty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=100)),
                ('unit_short_name', models.CharField(max_length=100)),
                ('allow_decimal', models.CharField(choices=[(0, 'Yes'), (1, 'No')], default=0, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='addproduct',
            name='unit',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.unit'),
        ),
    ]
