# Generated by Django 4.1.2 on 2023-10-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_unit_alter_addproduct_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='allow_decimal',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')]),
        ),
    ]
