# Generated by Django 4.1.2 on 2023-10-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_unit_allow_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='warranty_description',
            field=models.TextField(blank=True),
        ),
    ]
