# Generated by Django 4.1.2 on 2023-10-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_addproduct_category_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='warranty_duration_type',
            field=models.IntegerField(choices=[(0, 'Days'), (1, 'Months'), (2, 'Years')], default=0),
        ),
    ]
