# Generated by Django 4.1.2 on 2023-10-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_warranty_warranty_duration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_short_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
