# Generated by Django 4.1.2 on 2023-10-29 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_alter_unit_unit_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addproduct',
            name='sku',
            field=models.CharField(editable=False, max_length=36, unique=True),
        ),
    ]
