# Generated by Django 4.1.2 on 2023-11-01 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_productvariation_addproduct_product_variation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariationValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exc_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inc_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('margin_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('sku', models.CharField(blank=True, max_length=50, unique=True)),
                ('value', models.CharField(blank=True, max_length=50)),
                ('product_variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productvariation')),
            ],
        ),
    ]
