# Generated by Django 4.1.2 on 2023-11-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_productvariationvalue'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaxRate',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='applicable_tax_name',
            field=models.IntegerField(choices=[(0, 'Inclusive'), (1, 'Exclusive')], default=0),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product_type',
            field=models.IntegerField(choices=[(0, 'Single'), (1, 'Variable')], default=0),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='selling_price_tax_type',
            field=models.IntegerField(choices=[(0, 'Vat'), (1, 'SGST')], default=0),
        ),
        migrations.AddField(
            model_name='productvariationvalue',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
