# Generated by Django 4.2.6 on 2023-10-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='Paid_Status',
            field=models.IntegerField(choices=[(0, 'Checking'), (1, 'Payment Done'), (2, 'Due Running'), (3, 'Return Due Running')], default=0),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='Tax_Number',
            field=models.TextField(null=True, unique=True),
        ),
    ]
