# Generated by Django 4.2.6 on 2023-10-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_suppliers_paid_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='Tax_Number',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
