# Generated by Django 4.2.6 on 2023-10-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_suppliers_tax_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Action', models.IntegerField(choices=[(0, 'Action'), (1, 'Pay'), (3, 'View'), (4, 'Edit'), (5, 'Delete')], default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='suppliers',
            name='Action',
        ),
    ]
