# Generated by Django 4.2.6 on 2023-10-26 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_action_remove_suppliers_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact_ID', models.CharField(max_length=1000, unique=True)),
                ('Business_Name', models.CharField(max_length=1000)),
                ('Name', models.CharField(max_length=1000)),
                ('Email', models.EmailField(max_length=1000, unique=True)),
                ('Mobile', models.CharField(max_length=20, unique=True)),
                ('Delivery_Address', models.CharField(max_length=1000)),
                ('Home_Address', models.CharField(max_length=1000)),
                ('Tax_Number', models.TextField(blank=True, unique=True)),
                ('Credit_limit', models.TextField()),
                ('Reward_Point', models.TextField()),
                ('Customer_Group', models.CharField(max_length=1000)),
                ('Pay_Term', models.CharField(max_length=1000)),
                ('Opening_Balance', models.TextField()),
                ('Advance_Balance', models.TextField()),
                ('Total_Sale_Due', models.TextField()),
                ('Total_Sell_Return_Due', models.TextField()),
                ('Shipping_Address', models.CharField(max_length=1000)),
                ('Created_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='action',
            old_name='Action',
            new_name='Actions',
        ),
        migrations.AddField(
            model_name='suppliers',
            name='Created_At',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
